const types = {
    SET_PROJECT: 'SET_PROJECT',
    SET_LIVE_PROJECTS: 'SET_LIVE_PROJECTS',
    SET_LS_PROJECTS: 'SET_LS_PROJECTS',
    SET_YAML_CONTENT: 'SET_YAML_CONTENT',
    SET_PROJECTS_FROM_SELECT: 'SET_PROJECTS_FROM_SELECT',
    SET_PROJECTS_LOAD_PENDING: 'SET_PROJECTS_LOAD_PENDING',
    SET_PROJECTS_LOAD_COMPLETE: 'SET_PROJECTS_LOAD_COMPLETE',
};

export default types;
