const types = {
    SET_PROJECT: 'SET_PROJECT',
    SET_PROJECTS: 'SET_PROJECTS',
    SET_YAML_CONTENT: 'SET_YAML_CONTENT',
    SET_YAMLS_CONTENTS: 'SET_YAMLS_CONTENTS',
    SET_PROJECTS_LOAD_PENDING: 'SET_PROJECTS_LOAD_PENDING',
    SET_PROJECTS_LOAD_COMPLETE: 'SET_PROJECTS_LOAD_COMPLETE',
};

export default types;
