const types = {
    SET_CONTAINER: 'SET_CONTAINER',
    SET_CONTAINERS: 'SET_CONTAINERS',
    NEW_DOCKER_EVENTS: 'NEW_DOCKER_EVENTS',
    SET_CONTAINER_EXTRA_DATA: 'SET_CONTAINER_EXTRA_DATA',
};

export default types;
